<?php require_once 'header.phtml'; ?>

<div class="w-full max-w-sm mx-auto overflow-hidden bg-white rounded-lg shadow-md dark:bg-gray-800">
    <div class="px-6 py-4">
        <div class="flex justify-center mx-auto">
            <img class="w-auto h-7 sm:h-8" src="https://merakiui.com/images/logo.svg" alt="">
        </div>

        <h3 class="mt-3 text-xl font-medium text-center text-gray-600 dark:text-gray-200">Bienvenido</h3>

        <p class="mt-1 text-center text-gray-500 dark:text-gray-400">Crear cuenta</p>

        <form id="registerForm" action="registerUser" method="POST">
            <div class="w-full mt-4">
                <input id="name" name="nombre" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 focus:border-blue-400 dark:focus:border-blue-300 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300" type="text" placeholder="Nombre" aria-label="name" required/>
            </div>

            <div class="w-full mt-4">
                <input id="email" name="email" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 focus:border-blue-400 dark:focus:border-blue-300 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300" type="email" placeholder="Direccion Email" aria-label="Email Address" required/>
            </div>

            <div class="w-full mt-4">
                <input id="password" name="contrasenia" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-500 bg-white border rounded-lg dark:bg-gray-800 dark:border-gray-600 dark:placeholder-gray-400 focus:border-blue-400 dark:focus:border-blue-300 focus:ring-opacity-40 focus:outline-none focus:ring focus:ring-blue-300" type="password" placeholder="Contraseña" aria-label="Password" required/>
                <small id="passwordMessage" class="text-red-500 hidden">La contraseña debe contener al menos 8 caracteres, una letra mayúscula, una letra minúscula, un número y un carácter especial.</small>
            </div>

            <div class="flex items-center justify-between mt-4">
                <button class="px-6 py-2 text-sm font-medium tracking-wide text-white capitalize transition-colors duration-300 transform bg-blue-500 rounded-lg hover:bg-blue-400 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-50">
                    Crear cuenta
                </button>
            </div>

           <div>
                <?php if (isset($message)) : ?>
                    <p><?php echo $message; ?></p>
                <?php endif; ?>
           </div>
        </form>
    </div>

   <div class="flex items-center justify-center py-4 text-center bg-gray-50 dark:bg-gray-700">
        <span class="text-sm text-gray-600 dark:text-gray-200">Ya tienes cuenta? </span>

        <a href="login" class="mx-2 text-sm font-bold text-blue-500 dark:text-blue-400 hover:underline">Iniciar sesion</a>
    </div>
</div>

<?php require_once 'footer.phtml'; ?>
