<?php require_once 'header.phtml'; ?>

<div class="container mx-auto p-5">
    <h1 class="text-2xl font-bold mb-5">Crear Nueva Categoría</h1>
    
    <form action="addCategory" method="GET">
        <div class="mb-4">
            <label for="nombre" class="block text-gray-700">Nombre de la Categoría:</label>
            <input type="text" id="nombre" name="nombre" class="mt-2 block w-full px-4 py-2 border rounded" required>
        </div>

        <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Crear Categoría</button>
    </form>
</div>

<?php require_once 'footer.phtml'; ?>
