<?php require_once 'header.phtml'; ?>

<div class="container mx-auto p-5">
    <h1 class="text-2xl font-bold mb-5">Lista de Productos</h1>
    
    <?php if (!empty($products)): ?>
        <ul class="list-disc pl-5">
            <?php foreach ($products as $product): ?>
                <?php include 'components/ProductCard.php'; ?>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>No hay productos disponibles.</p>
    <?php endif; ?>
</div>

<?php require_once 'footer.phtml'; ?>